# for getting new LSP
# https://github.com/helix-editor/helix/wiki/Language-Server-Configurations


# QOL LSP
# introduce new language server

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]
indent = { tab-width = 4, unit = "    " }

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = true
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "python"
language-servers = ["ruff"]
auto-format = true
[language-server.ruff]
command = "ruff"
args = ["server"]
# [language-server.pylyzer]
# command = "pylyzer"
# config = { settings = { args = ["--server"] } }

[[language]]
name = "lua"
language-servers = ["lua-language-server"]
auto-format = true

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls"]
file-types = ["md", "txt"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true
comment-tokens = ["-", "+", "*", ">", "- [ ]"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls.linters]
long_sentences = false
avoid_curses = false

[language-server.harper-ls.config.harper-ls]
diagnosticSeverity = "warning"
userDictPath = "~/.config/harper/dict.txt"
fileDictPath = "~/.harper/"

[language-server.superhtml-lsp]
command = "superhtml"
args = ["lsp"]

[[language]]
name = "html"
scope = "source.html"
roots = []
file-types = ["html"]
language-servers = ["superhtml-lsp"]
auto-format = true

[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]
auto-format = true
file-types = ["json"]

[[language]]
name = "css"
file-types = ["scss", "css"]
auto-format = true
language-servers = ["vscode-css-language-server"]
